ALTER TABLE agents ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS bio TEXT;
